#!/usr/bin/expect -f
set timeout -1
set password "G?-fT3\{,+c7x^#SH"
set ip "43.155.250.122"
set port "23456"

spawn scp -o StrictHostKeyChecking=no -P $port remote_deploy.sh ubuntu@$ip:/home/ubuntu/
expect {
    "*assword:*" {
        send "$password\r"
        exp_continue
    }
    eof
}

spawn ssh -o StrictHostKeyChecking=no -p $port ubuntu@$ip "chmod +x remote_deploy.sh && ./remote_deploy.sh"
expect {
    "*assword:*" {
        send "$password\r"
        exp_continue
    }
    eof
}
